# -*- coding: utf-8 -*-

"""Unit tests for the ingestion actor"""

import pytest
from thespian.actors import ActorSystem, ActorExitRequest
from cb_binary_analysis.report_actor import ReportActor
from cbapi.psc.threathunter import CbThreatHunterAPI
from utils.CBAPIMock import CBAPIMock

ENGINE_NAME = "TEST_ENGINE"
FEED_ID = "1"


@pytest.fixture(scope="session")
def cb_threat_hunter():
    """Create CbThreatHunterAPI singleton"""
    return CbThreatHunterAPI(url="https://example.com",
                             org_key="test",
                             token="abcd/1234",
                             ssl_verify=False)


@pytest.fixture(scope="function")
def actor(cb_threat_hunter):
    """Creates actor to unit test"""
    actor = ActorSystem().createActor(ReportActor)

    ActorSystem().ask(actor, cb_threat_hunter)
    ActorSystem().ask(actor, ENGINE_NAME)
    yield actor
    ActorSystem().ask(actor, ActorExitRequest())


@pytest.fixture(scope="function")
def cbapi_mock(monkeypatch, cb_threat_hunter):
    """Mocks CBAPI for unit tests"""
    return CBAPIMock(monkeypatch, cb_threat_hunter)


@pytest.mark.parametrize("input", [
    [{
        "id": "j39sbv7",
        "match_type": "equality",
        "values": ["127.0.0.1"],
        "severity": 1,
    }],
    [{
        "id": "j39sbv7",
        "match_type": "equality",
        "values": ["127.0.0.1"],
        "severity": 1,
    },
        {
        "id": "slkf038",
        "match_type": "equality",
        "values": ["app.exe"],
        "severity": 10,
    }],
])
def test_receiveMessage_ask(actor, cbapi_mock, input):
    """Test receiveMessage"""
    for ioc in input:
        valid = ActorSystem().ask(actor, ioc, 1)
        assert valid is True

    # Mock report put and send request body back
    cbapi_mock.mock_request("PUT", f"/threathunter/feedmgr/v2/orgs/test/feeds/{FEED_ID}/reports/.*", None)

    ActorSystem().ask(actor, ("SEND_REPORTS", FEED_ID), 1)
    assert "TEST_ENGINE" in cbapi_mock._last_request_data["title"]
    assert cbapi_mock._last_request_data["description"] == "Automated report generated by Binary Analysis SDK"
    # assert cbapi_mock._last_request_data["iocs_v2"] == input


@pytest.mark.parametrize("input", [
    [{
        "id": "j39sbv7",
        "match_type": "equality",
        "values": ["127.0.0.1"],
        "severity": 1,
    }],
    [{
        "id": "j39sbv7",
        "match_type": "equality",
        "values": ["127.0.0.1"],
        "severity": 1,
    },
        {
        "id": "slkf038",
        "match_type": "equality",
        "values": ["app.exe"],
        "severity": 10,
    }],
])
def test_receiveMessage_tell(actor, cbapi_mock, input):
    """Test receiveMessage"""
    for ioc in input:
        ActorSystem().tell(actor, ioc)
        valid = ActorSystem().listen()
        assert valid is True
